# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_banner_emailverifyrecord_friendlylink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.IntegerField(blank=True, null=True, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.IntegerField(blank=True, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='填写电子邮箱用于密码找回', max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=1, max_length=10, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
