# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20181111_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alipay',
            field=models.ImageField(blank=True, help_text='支付宝支付', null=True, upload_to='pay/alipay/%Y/%m', verbose_name='支付宝支付'),
        ),
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_fiends',
            field=models.ImageField(blank=True, help_text='添加微信好友', null=True, upload_to='wechat/%Y/%m', verbose_name='微信好友'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_pay',
            field=models.ImageField(blank=True, help_text='微信支付', null=True, upload_to='pay/wechat/%Y/%m', verbose_name='微信支付'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='填写电子邮箱用于密码找回', max_length=254, unique=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=10, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=2, verbose_name='性别'),
        ),
    ]
