# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('profile', models.TextField(max_length=200, verbose_name='文章简介')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='文章正文')),
                ('tags', models.CharField(help_text='标签用于keywords，方便搜索引擎找到你', max_length=15, verbose_name='文章标签')),
                ('view_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('admire_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '文章表',
                'db_table': 'article_articel',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('content', models.TextField(default='', verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='对那个文章的评论')),
            ],
            options={
                'verbose_name': '文章评论',
                'db_table': 'article_comment',
            },
        ),
    ]
