# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181111_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='profile',
        ),
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default=1, help_text='上传个性图片，让您的文章更受欢迎', upload_to='cover/%Y/%m', verbose_name='文章封面'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='文章正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(help_text='请提取文章的关键字，方便文章被找到', max_length=15, verbose_name='文章标签'),
        ),
    ]
