# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_banner_emailverifyrecord_friendlylink'),
        ('article', '0003_auto_20181111_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Type', verbose_name='文章类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, help_text='上传个性图片，让您的文章更受欢迎', null=True, upload_to='cover/%Y/%m', verbose_name='文章封面'),
        ),
    ]
